# Generated by Django 4.2 on 2023-04-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_dyplomowa', '0002_remove_user_user_id'),
    ]

    operations = [
    ]
