# Generated by Django 4.2 on 2023-04-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_dyplomowa', '0003_auto_20230422_1904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
