# Generated by Django 4.2 on 2023-05-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_dyplomowa', '0007_alter_projects_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=16)),
                ('file', models.FileField(upload_to='')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja_dyplomowa.projects')),
            ],
        ),
    ]
