# Generated by Django 4.2 on 2023-05-06 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplikacja_dyplomowa', '0008_mainfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mainfiles',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectobjects',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tags',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('file_name', 'project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='mainfiles',
            unique_together={('file_name', 'project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='projectobjects',
            unique_together={('object_name', 'project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together={('project_name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('tag_name', 'project', 'user')},
        ),
    ]
