# Generated by Django 4.2 on 2023-05-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja_dyplomowa', '0011_alter_tags_unique_together_remove_tags_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='tags',
        ),
    ]
